- name: install nginx
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
    - name: start service
      service:
        name: nginx
        state: started
    - name: add line in index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Hello this line is added in this file"
    