- name: install nginx
  hosts: all
  become: yes
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: start service
      service:
        name: nginx
        state: started
    - name: add line in index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Hello this line is added in this file"
    - name: Add Nginx server block
      blockinfile:
        path: /var/www/html/index.html
        block: |
          <h2>Hello world!</h2>
          <p>Hello world!</p>
        marker: "# {mark} ANSIBLE MANAGED SERVER BLOCK"